services:
  pgserver:
    image: postgres:12
    environment:
      - "POSTGRES_DB=mesures"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "/usr/bin/pg_isready", "--dbname=mesures"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - internal
      
  tomee:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      pgserver:
        condition: service_healthy
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal: